#!/usr/bin/env python3
"""
Plot IPC throughput results produced by xv6 `pipebench`.

Input file format (text, generated by `pipebench` and saved to ipctp.txt
inside the xv6 fs):

    # xaxis=chunk_bytes total_bytes=4194304
    64 1234567
    128 2345678
    256 4567890
    ...

Workflow:
    1. Inside xv6:   pipebench           # writes ipctp.txt
                     cat ipctp.txt       # prints content to console
    2. Copy the printed lines into a file on the host, e.g. ipctp.txt
    3. On host:      python3 tools/plot_throughput.py ipctp.txt

Usage:
    python3 tools/plot_throughput.py [input.txt] [-o output.png] [--show]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


def parse_data(path: Path):
    header = ""
    points: list[tuple[int, int]] = []
    with path.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            if line.startswith("#"):
                if not header:
                    header = line.lstrip("#").strip()
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            try:
                label = int(parts[0])
                value = int(parts[1])
            except ValueError:
                continue
            points.append((label, value))
    return header, points


def detect_xlabel(header: str, default: str = "x") -> str:
    if "xaxis=" in header:
        for token in header.split():
            if token.startswith("xaxis="):
                return token.split("=", 1)[1]
    return default


def plot(points, header, output: Path | None, show: bool):
    try:
        import matplotlib
        if not show:
            matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        sys.exit(
            "matplotlib not installed. Run: pip install matplotlib"
        )

    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    ys_kb = [v / 1024.0 for v in ys]

    xlabel = detect_xlabel(header, default="parameter")
    title = "xv6 pipe IPC throughput"
    if header:
        title = f"{title}\n({header})"

    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    # Bar chart
    ax = axes[0]
    positions = list(range(len(xs)))
    ax.bar(positions, ys_kb, color="#3b82f6")
    ax.set_xticks(positions)
    ax.set_xticklabels([str(x) for x in xs], rotation=30)
    ax.set_xlabel(xlabel)
    ax.set_ylabel("Throughput (KB/s)")
    ax.set_title("Bar chart")
    for i, v in enumerate(ys_kb):
        ax.text(i, v, f"{v:.0f}", ha="center", va="bottom", fontsize=8)

    # Line chart
    ax = axes[1]
    ax.plot(xs, ys_kb, marker="o", color="#ef4444")
    ax.set_xscale("log", base=2)
    ax.set_xlabel(f"{xlabel} (log2)")
    ax.set_ylabel("Throughput (KB/s)")
    ax.set_title("Line chart")
    ax.grid(True, which="both", linestyle=":", alpha=0.5)
    for x, y in zip(xs, ys_kb):
        ax.annotate(f"{y:.0f}", (x, y), textcoords="offset points",
                    xytext=(0, 6), ha="center", fontsize=8)

    fig.suptitle(title)
    fig.tight_layout()

    if output:
        fig.savefig(output, dpi=150)
        print(f"Saved chart to {output}")
    if show or not output:
        plt.show()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Plot xv6 pipe IPC throughput results."
    )
    parser.add_argument(
        "input",
        nargs="?",
        default="ipctp.txt",
        help="Path to throughput data file (default: ipctp.txt)",
    )
    parser.add_argument(
        "-o", "--output",
        default="ipctp.png",
        help="Output PNG path (default: ipctp.png)",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Open an interactive window in addition to saving.",
    )
    args = parser.parse_args()

    path = Path(args.input)
    if not path.exists():
        sys.exit(f"Input file not found: {path}")

    header, points = parse_data(path)
    if not points:
        sys.exit(f"No data points parsed from {path}")

    print(f"Loaded {len(points)} points from {path}")
    if header:
        print(f"Header: {header}")
    for label, value in points:
        print(f"  {label:>8d}  {value:>12d} B/s ({value/1024:.1f} KB/s)")

    out = Path(args.output) if args.output else None
    plot(points, header, out, args.show)


if __name__ == "__main__":
    main()
